{% set name = "log4cpp" %}
{% set version = "1.1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: 'https://downloads.sourceforge.net/project/log4cpp/log4cpp-1.1.x (new)/log4cpp-1.1/{{ name }}-{{ version }}.tar.gz'
  sha256: 2cbbea55a5d6895c9f0116a9a9ce3afb86df383cd05c9d6c1a4238e5e5c8f51d
  patches:
    - osx_remove_manual_test.patch  # [osx]

build:
  number: 0
  skip: True  # [win and py35]
  detect_binary_files_with_prefix: True
  features:
    - vc14  # [win]

requirements:
  build:
    - automake  # [unix]
    - cmake  # [win]
    - libtool  # [unix]
    - python >=3.5  # [win]
    - toolchain
    - vc 14  # [win

  run:
    - vc 14  # [win]

test:
  commands:
    - test -f $PREFIX/include/log4cpp/Category.hh  # [unix]
    - test -f $PREFIX/lib/liblog4cpp.a  # [unix]
    - test -f $PREFIX/lib/liblog4cpp${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\include\\log4cpp\\Category.hh exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\log4cpp.lib exit 1  # [win]
    - conda inspect linkages -p $PREFIX libusb  # [not win]
    - conda inspect objects -p $PREFIX libusb  # [osx]

about:
  home: http://log4cpp.sourceforge.net
  license: LGPL-2.1
  license_file: COPYING
  summary: 'C++ library for flexible logging'
  description: |
    Log for C++ is a library of C++ classes for flexible logging to files,
    syslog and other destinations. It is modeled after the Log for Java library
    (http://jakarta.apache.org/log4j/), staying as close to their API as is
    reasonable.
  doc_url: http://log4cpp.sourceforge.net/api/index.html
  dev_url: http://git.code.sf.net/p/log4cpp/codegit

extra:
  recipe-maintainers:
    - ryanvolz
