channels:
  sources:
  - conda-forge
  - ryanvolz
  - defaults
  targets:
  - [ryanvolz, main]
github:
  user_or_org: ryanvolz
travis:
  secure:
    BINSTAR_TOKEN: debUkYqIUAVL7Zag5rLUz+n+xa+s+6z/VuMydnm9zzibZR1ZcBCBfL/71PBVsCiKXLzAoTpkuflrZigePcnq/UtfhIQH1Iah4OdjXUE8r8xdufW5mXqRMmK1TdNNufHcbp08/2UykId4aOwmYXZjZSIykDsAekwac3WQAcueEmkUuZvdvTma0hKnjCGrSSjcCqWtDZRRwDdOSYk7Mza56cohVu24KG2zzlYhHX5lK0ivOZgghv0MFzVS0ImGBoNrL8zK6f4NeXadIIwuixz6ycbITjMr5mmiLZnstl2rrV9oQTegAa3vz2J+vwx18a8ejSL4cnkSRlPVHIp+izh9Jr6YEPkAGyXh/dHaCwsHS1ptqRO+AWW+9If288nl1Q+KLZDIGRca/yLDqaz51DRgvMRFyJie/0u3LZ4nMvImFin6snjxl+3ROiZLMYaR2JMTo3nqoHBil09yCjv802Sfn//jq09VLnL9q9IexuJ5gg4myz5BBJrvmNxlL055GAyrktMAXMCeei99ssT+I3P+q5OPUdAycewcNIIZLZ8DaT8FbXfsXmKi9Mj2L3H4lvOqquBTyE/db2lChfVHcO2KCu/1ImkEAMM+FrTRqWQvCQOxv0CX2q16Cc5ldVDy9UKnSmD8iSOZx4avzbbPzh/pzho7KIXcUD4Ajg2r6VG1b78=
appveyor:
  secure:
    BINSTAR_TOKEN: 71TfwwHlSXL1lpYe3qfRuCAgxnXZkZw1a89oCIgAz4T+pKtbztMaAfWiC4oMSy2B
